add set type
hstream-io/hesp pull request #7
Opened 2020-05-18 20:29 UTC by MaboroshiChan

2020-05-19 07:00 UTC, 4eUeP requested changes

2020-05-19 07:00 UTC, 4eUeP commented on hesp.cabal
> +
?

2020-05-19 07:00 UTC, 4eUeP commented on src/Network/HESP/Protocol.hs
> +import           Data.Set               (empty, toList)
> These modules are intended to be imported qualified, to avoid name clashes with Prelude functions...

Use `S.Set`, `S.empty`, `S.toList` instead (and remove the last two imports)

2020-05-19 07:00 UTC, 4eUeP commented on src/Network/HESP/Protocol.hs
> +serialize (MatchSet xs)           = serializeSet xs
run `stylish-haskell` to format

2020-05-19 07:00 UTC, 4eUeP commented on hesp.cabal
> +  build-depends:      base >= 4.11 && < 5, bytestring ^>= 0.10, hesp, hspec, text ^>= 1.2, containers     ^>= 0.6
run `stylish-cabal` to format

2020-05-19 07:00 UTC, 4eUeP commented on src/Network/HESP/Protocol.hs
> +
?

2020-05-19 07:00 UTC, 4eUeP commented on src/Network/HESP/Protocol.hs
> +                          (c:cs) -> serialize (c) <> go (cs)
remove `()`

2020-05-19 07:00 UTC, 4eUeP commented on src/Network/HESP/Protocol.hs
> +serializeSet ms = serialize' (toList ms) where
start a new line

2020-05-19 07:00 UTC, 4eUeP commented on src/Network/HESP/Protocol.hs
> +set = fmap (foldr (\m-> \s-> S.insert m s) (Data.Set.empty) ) array
`\m s -> ...`

2020-05-19 07:00 UTC, 4eUeP commented on src/Network/HESP/Protocol.hs
> +
?

2020-05-19 07:00 UTC, 4eUeP commented on src/Network/HESP/Types.hs
> +import           Data.Set               (empty)
use `S.Set` ...

2020-05-19 07:00 UTC, 4eUeP commented on test/Test/ProtocolSpec.hs
> +import Data.Set (fromList)
`stylish-haskell`

2020-05-20 01:30 UTC, MaboroshiChan commented on hesp.cabal
> +
what is this?

2020-06-09 01:22 UTC, closed without merging